import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1500, height: 950 } });
page.on('pageerror', e => console.log('PAGE EXCEPTION:', e.message));
await page.goto('file://<repo>/Editor/dist-openstudio-editor.html');
await page.waitForTimeout(900);
await page.screenshot({ path: 'out/30-empty-state.png' });
await page.setInputFiles('#dirInput', '<repo>/test/fixture.osrec');
await page.waitForFunction(() => !document.getElementById('exportBtn').disabled, { timeout: 20000 });
await page.evaluate(() => { pause(); seekTo(2.6); S.selSeg = 0; updateZoomPanel(); drawTimeline(); });
await page.waitForTimeout(700);
await page.screenshot({ path: 'out/31-main-ui.png' });
await page.click('#exportChip');
await page.waitForTimeout(450);
await page.screenshot({ path: 'out/32-popover.png' });
await page.keyboard.press('Escape');
await page.evaluate(() => { document.getElementById('shortcuts').classList.add('open'); });
await page.waitForTimeout(400);
await page.screenshot({ path: 'out/33-shortcuts.png' });
await browser.close();
console.log('SHOTS DONE');
